"use client";
import { useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { WILAYAS } from "@/lib/wilayas";

export default function CustomerRegister() {
  const params = useSearchParams();
  const next = params.get("next") || "/";
  const [form, setForm] = useState({ name: "", phone: "", password: "", confirmPassword: "", wilaya: "", city: "", address: "" });
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const set = (key) => (e) => setForm((v) => ({ ...v, [key]: e.target.value }));
  async function submit(e) { e.preventDefault(); setError(""); if (!form.name.trim()) return setError("الاسم مطلوب."); if (form.password !== form.confirmPassword) return setError("كلمتا المرور غير متطابقتين."); setBusy(true); try { const r = await fetch("/api/customer/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) { setError(d.error || "تعذر إنشاء الحساب."); return; } window.location.href = next; } catch { setError("تعذر الاتصال بالخادم."); } finally { setBusy(false); } }
  return <main dir="rtl" className="min-h-screen bg-[#f7f8f4] p-4 flex items-center justify-center"><form onSubmit={submit} className="w-full max-w-lg bg-white rounded-3xl p-6 shadow-sm border border-gray-200 space-y-4"><div><h1 className="text-2xl font-black">إنشاء حساب</h1><p className="text-gray-500 mt-1">أنشئ حسابك برقم هاتفك الجزائري.</p></div>{error && <div className="rounded-xl bg-red-50 text-red-700 p-3">{error}</div>}<input required value={form.name} onChange={set("name")} placeholder="الاسم الكامل" className="w-full rounded-xl border p-3" /><input required value={form.phone} onChange={set("phone")} placeholder="رقم الهاتف" className="w-full rounded-xl border p-3" inputMode="tel" /><input required minLength={8} type="password" value={form.password} onChange={set("password")} placeholder="كلمة المرور (8 أحرف على الأقل)" className="w-full rounded-xl border p-3" /><input required minLength={8} type="password" value={form.confirmPassword} onChange={set("confirmPassword")} placeholder="تأكيد كلمة المرور" className="w-full rounded-xl border p-3" /><select required value={form.wilaya} onChange={set("wilaya")} className="w-full rounded-xl border p-3 bg-white"><option value="">اختر الولاية</option>{WILAYAS.map(w => <option key={w}>{w}</option>)}</select><input required value={form.city} onChange={set("city")} placeholder="المدينة / البلدية" className="w-full rounded-xl border p-3" /><textarea value={form.address} onChange={set("address")} placeholder="العنوان (اختياري)" className="w-full rounded-xl border p-3 min-h-24" /><button disabled={busy} className="w-full rounded-xl bg-black text-white p-3 font-bold">{busy ? "جاري الإنشاء…" : "إنشاء الحساب"}</button><p className="text-sm text-center">لديك حساب؟ <Link className="underline font-bold" href={`/customer/login?next=${encodeURIComponent(next)}`}>تسجيل الدخول</Link></p></form></main>;
}
